apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-chat
  template:
    metadata:
      labels:
        app: fastapi-chat
    spec:
      containers:
      - name: fastapi-chat
        image: stradivirus/chatting
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-chat-service
spec:
  selector:
    app: fastapi-chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer