apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: chat
spec:
  serviceName: kafka-service
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: init
        image: busybox
        command: ['sh', '-c', 'echo $(echo ${POD_NAME} | awk -F"-" "{print \$NF}") > /mnt/volume/node-id']
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: node-id
          mountPath: /mnt/volume
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 9093
          name: controller
        env:
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CFG_NODE_ID
          valueFrom:
            configMapKeyRef:
              name: kafka-node-id
              key: node-id
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "0@kafka-0.kafka-service.chat.svc.cluster.local:9093,1@kafka-1.kafka-service.chat.svc.cluster.local:9093,2@kafka-2.kafka-service.chat.svc.cluster.local:9093"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-node-id
              key: node-id
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: "LQaaEvc3RBGAT43AUcbH7g"  # 클러스터 ID를 명시적으로 설정
        volumeMounts:
        - name: node-id
          mountPath: /mnt/volume
      volumes:
      - name: node-id
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: chat
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: kafka
  - port: 9093
    name: controller
  selector:
    app: kafka

