apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: chat
data:
  server.properties: |
    process.roles=broker,controller
    node.id=0
    controller.quorum.voters=0@kafka-0.kafka-service.chat.svc.cluster.local:9093,1@kafka-1.kafka-service.chat.svc.cluster.local:9093,2@kafka-2.kafka-service.chat.svc.cluster.local:9093
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    inter.broker.listener.name=PLAINTEXT
    advertised.listeners=PLAINTEXT://kafka-0.kafka-service.chat.svc.cluster.local:9092
    listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    log.dirs=/bitnami/kafka/data
    num.partitions=1
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: chat
spec:
  serviceName: kafka-service
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 9093
          name: controller
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: KAFKA_CFG_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "0@kafka-0.kafka-service.chat.svc.cluster.local:9093,1@kafka-1.kafka-service.chat.svc.cluster.local:9093,2@kafka-2.kafka-service.chat.svc.cluster.local:9093"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        volumeMounts:
        - name: config
          mountPath: /opt/bitnami/kafka/config/server.properties
          subPath: server.properties
      volumes:
      - name: config
        configMap:
          name: kafka-config

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: chat
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: kafka
  - port: 9093
    name: controller
  selector:
    app: kafka
