apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongodb_uri: mongodb+srv://stradivirus:1q2w3e4r%21%21@cluster0.e7rvfpz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0